### ISSUE TITLE
Sticky

### ISSUE THREAD

**Issue by Dezignwhiz** [Mottie/Jatt#2]
Hey.. I've added the class sticky to my anchor tag so that the users can copy the text within tooltip. The issue I'm seeing here is the tooltip is not hiding itself when there is no hover. we should manually close the tooltip now by clicking the close button at top. Can we show it only when it is hovered and hide when the mouse is no longer on it? thanks.

**Comment by Mottie** [comment]
Ok, try this ([demo](http://jsfiddle.net/Mottie/UMAEK/)):

``` js
$.jatt();

$(document).bind('revealed.jatt', function(e, tt){
    if ($(tt).hasClass('sticky')) {
        // remove when mouse leaves the tooltip
        $('#tooltip').bind('mouseleave', function(){
            $.jatt.removeTooltips();
        });
    }
});
```

---

UPDATE: In v2.9.0, the triggered events were renamed, so use this code now ([demo](http://jsfiddle.net/Mottie/UMAEK/1/)):

``` js
$.jatt();

$(document).bind('jatt-reveal', function(e, tt){
    if ($(tt).hasClass('sticky')) {
        // remove when mouse leaves the tooltip
        $('#tooltip').bind('mouseleave', function(){
            $.jatt.removeTooltips();
        });
    }
});
```
